export const STR = {
  brandFallback: 'Chat',
  close: 'Fechar chat',
  inputPlaceholder: 'Mensagem',
  inputLabel: 'Escreva sua mensagem',
  send: 'Enviar mensagem',
  attach: 'Anexar arquivo',
  attachCamera: 'Câmera',
  attachGallery: 'Fotos e vídeos',
  attachDocument: 'Documento',
  attachAudio: 'Áudio',
  recordAudio: 'Gravar áudio',
  sendAudio: 'Enviar áudio',
  cancelRecording: 'Cancelar gravação',
  recording: 'Gravando…',
  recordTooShort: 'Gravação muito curta.',
  micDenied: 'Permita o acesso ao microfone para gravar.',
  micUnavailable: 'Nenhum microfone encontrado.',
  audioFailed: 'Não foi possível gravar o áudio.',
  playAudio: 'Reproduzir áudio',
  pauseAudio: 'Pausar áudio',
  dismissNotice: 'Fechar aviso',
  sending: 'Enviando…',
  sent: 'Enviado',
  notDelivered: 'Não entregue',
  retry: 'Tentar de novo',
  reconnecting: 'Reconectando…',
  historyError: 'Não foi possível carregar a conversa.',
  tryAgain: 'Tentar novamente',
  startError: 'Não foi possível iniciar o chat.',
  fileTooLarge: (limit: string) => `Arquivo muito grande (máx. ${limit}).`,
  fileUnsupported: 'Tipo de arquivo não suportado.',
  documentLabel: 'Documento',
  openFile: 'Abrir',
  imageAlt: 'Imagem enviada na conversa',
  videoUnsupported: 'Seu navegador não reproduz este vídeo.',
  loadingOlder: 'Carregando mensagens…',
  poweredBy: 'Powered by',
  back: 'Voltar para os atendimentos',
  inProgress: 'Em andamento',
  closed: 'Encerrado',
  you: 'Você',
  imageLabel: 'Imagem',
  audioLabel: 'Áudio',
  videoLabel: 'Vídeo',
  newMessage: 'Nova mensagem',
  newConversation: 'Nova conversa',
  loadMore: 'Ver atendimentos anteriores',
  conversationsError: 'Não foi possível carregar seus atendimentos.',
  noConversations: 'Você ainda não tem atendimentos por aqui.',
  closedAt: (when: string) => `Atendimento encerrado · ${when}`,
  closedPlain: 'Atendimento encerrado',
  protocol: (value: string) => `Protocolo ${value}`,
  preChatTitle: 'Antes de começar',
  preChatIntro: 'Conte pra gente quem você é — assim o atendimento já começa do jeito certo.',
  preChatName: 'Nome',
  preChatEmail: 'E-mail',
  preChatPhone: 'Telefone',
  preChatDocument: 'CPF/CNPJ',
  preChatRequired: 'Preencha este campo.',
  preChatEmailInvalid: 'Informe um e-mail válido.',
  preChatSubmit: 'Iniciar conversa',
  typing: 'digitando…',
  viewOptions: 'Ver opções',
  closeSheet: 'Fechar',
  copyCode: 'Copiar código',
  codeCopied: 'Código copiado',
  pixTitle: 'Pagamento PIX',
};

export const MEDIA_LABELS: Record<string, string> = {
  image: STR.imageLabel,
  sticker: STR.imageLabel,
  audio: STR.audioLabel,
  voice: STR.audioLabel,
  video: STR.videoLabel,
  document: STR.documentLabel,
};
